server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8083/eureka

spring:
  application:
    name : gateway
  cloud:
    gateway:
      routes:
        - id: counterServices
          uri: lb://COUNTER-SERVICES
          predicates:
            - Path=/counter/**


